version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    networks:
      - internal_network
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - /home/ubuntu/clickhouse-data:/var/lib/clickhouse

  activated-carbon-analytics-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: ariaskov/activated-carbon-analytics-server
    networks:
      - internal_network
    ports:
      - "3010:3000"
    depends_on:
      - clickhouse

  activated-carbon-analytics-ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
      args:
        - SERVER_ENDPOINT=https://ac-analytics.toivo.tech
    image: ariaskov/activated-carbon-analytics-ui
    ports:
      - "3011:80"
    depends_on:
      - activated-carbon-analytics-server

networks:
  internal_network:
    driver: bridge
